<script type='text/javascript'>

$('#saveForum').live('click', function()  
{	
	$.post("<?php echo $this->baseUrl();?>/forum/index/submit", {title: $('#title').val(), description: $('#contentBody').val()},
	function(data)
	{
		alert(data);
		location.reload();
	}, "text");
});
</script>

<div  class="titleWindow "> 
	<div id="titleText">
    	<span><?php echo $this->translate('Create Forum'); ?></span></div>
</div>
<div>

<table class="popup_table" cellspacing='0' cellpadding='10' width="500px">

			<tr>	
				<td>
					  <label><?php echo $this->translate('Forum name'); ?></label>
				</td>
				
				<td class="alt"><input type="text" width="100%" id="title" class="forum_subject_field"/></td>
				
			</tr>
			
			<tr>	
				<td valign="top">
                	<label><?php echo $this->translate('Description'); ?></label>
				</td>
				
				<td class="alt">
					<div class="post_body">
                        <div>
                            <textarea rows="7"  id="contentBody" name="body" style="width:400px"> </textarea>
                        </div>
                    </div>
				</td>
			
			</tr>
			<tr>
			
			  <td>&nbsp;</td>
			  <td class="alt"><div id="saveForum" class="buttons"><a href="javascript::void()">
			  <img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/tick.png" alt=""/>
			   <?php echo $this->translate('Submit'); ?></a></div></td>
  </tr>
			

			</table>
	</div>