<head>
	<title><?php echo $this->company_name; ?>  <?php echo $this->translate("Intranet");?></title>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/js/jquery/jquery.js"></script>
	
	<?php echo $this->headLink();?>

</head>
<body class="install_body">
<div class="wrapper " align="center">
	<div id="install_container" >
		<div class="box_D_noMargin rounded" style="height: 210 ;">
			<div class="appPad">
				 <div id="helpdesk_main">
						 <img src="<?php echo $this->baseUrl();?>/uploads/logo.png" alt="Precurio"/><br/>
						 <span style="font-weight: bold;font-size: 11px;padding: 0px 0px 0px 20px;">
						 ....your complete intranet solution
						 </span>
						 <div id="noRecords" align="center">
							 <a type="submit" class="mild" href="<?php echo $this->baseUrl();?>/install/install/login/">
						                
						         <?php echo $this->translate("Click here to login");?>  
						    </a>
					    </div>
				   </div> 
			  </div>
		</div>	   
	</div>        
</div>
</body>