<head>
	<title><?php echo $this->company_name; ?>  <?php echo $this->translate("Intranet");?></title>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/js/jquery/jquery.js"></script>
	
	<?php echo $this->headLink();?>

</head>
<?php $selected = $this->page;?>
<body class="install_body">

<div class="wrapper " align="center">

	<div id="install_container" >
 
	<div id="full_bar">
		<div class="box_D_noMargin rounded" style="height: <?php echo ($selected ==  'mail') ? 780 :($selected=='ldap' || $selected=='module' || $selected=='general' ? 670 : 520); ?> ;">
			<div class="appPad">
				 <div id="helpdesk_main">
					 
			         	<div class="contentPad_noLineHeight" >
			         		
			                <span class="adminHeader"><?php 	echo $this->pageTitle; ?></span>
			                
			                    <div id="admin_body">
			                        <div class="contentPad_noLineHeight">
										<div  id="tab" class="appTabs">
										<?php
										$root = Zend_Registry::get('root');
										require_once($root.'/application/install/views/scripts/check_settings.phtml')
										?>
											<div >
												<?php if($selected != 'newuser') require_once('setting_tabs.phtml'); ?>
												<br />
											 </div>
											 <div id="form">
											 <?php require_once($selected .'.phtml'); ?> 
											 </div>
									 	</div> 
			                        </div>
			                         
			               	</div>
			            </div>
				 </div>
			</div>
		</div>
	</div>
	</div>    
</div>         
</body>
	<?php echo $this->headScript();?>