	
	<?php 
	
	function generateTable($arr,$header,$pathToController)
	{
		$translate = Zend_Registry::get('Zend_Translate');
		$str = "<table border='1' width='100%'>";

		
		$str .= "<tr>";
		foreach($header as $i)
		{
			$str .= "<th>$i </th>";
		}
		$str .= "<th></th>";
		$str .= "<th></th>";
		$str .= "<th><input type='checkbox' name='id' id='id'   onclick='selectAll(this)'>
		</th>";
		$str .= "</tr>";
		
		foreach($arr as $value)
		{
			$str .= "<tr>";
			$key = $value['id'];
			foreach($value as $prop=>$j)
			{
				if($prop === "id")continue;
				$str .= "<td>$j </td>";
			}
			$str .= "<td><a href='{$pathToController}activate/id/{$key}'>".$translate->translate('Activate')."</a></td>";
			$str .= "<td><a href='{$pathToController}view/id/{$key}'>".$translate->translate('View Styles')."</a></td>";
			$str .= "<td><input type='checkbox' name='ids[]' id='ids[]'  value='$key'>
			</td>";
			$str .= "</tr>";
		}
		$str .= "</table>";
		return $str;
	}

	?>

	<?php 
	$pathToController = $this->baseUrl().$this->pathToController;

	require_once 'Zend/Paginator.php';
	$paginator = Zend_Paginator::factory($this->list);
	$paginator->setCurrentPageNumber($this->cpage);
	$paginator->setItemCountPerPage(10);
	$this->paginator = $paginator;
	?>
	<form method="post" name="searchListForm" id="searchListForm" action="<?php echo $pathToController."index" ?> ">
		<input id="table" name="table" value="<?php echo $this->table;?>" type="hidden">
		<table class="ewBasicSearch">
			<tbody><tr>
				<td>
					<input name="search" id="search" size="20" value="<?php echo $this->searchText;?>" type="text">
					<input name="Submit" id="Submit" value="<?php echo $this->translate("Search");?> (*)" type="Submit">&nbsp;
					<a href="<?php echo $this->pathToController;?>"><?php echo $this->translate("Show all");?></a>&nbsp;
				</td>
			</tr>
			</tbody>
		</table>
	</form>
	<span id="adminList">
		<div class="buttons">
		<a href="<?php echo $pathToController."new"?>" class="mild" rel="facebox"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/add.png" alt=""/>  <?php echo $this->translate("Install Theme");?></a>&nbsp;&nbsp;
		<a href="" onclick="if (!keySelected(document.listForm)) alert('<?php echo $this->translate("No records selected");?>'); else {document.listForm.action='<?php echo $pathToController."delete" ?>';document.listForm.submit();};return false;" class="mild"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/delete.png" alt=""/>  <?php echo $this->translate("Delete Selected Themes");?></a>&nbsp;&nbsp;
		
		</div>
	</span>
	<br />  <br /> 
	
	<div id="adminTable"> 
	
	<?php echo $this->paginationControl($this->paginator, 'Elastic'); ?>
	<form action="" name="listForm" id="listForm" method="post"> 
		<?php 
			if($paginator->getCurrentItemCount())
			{
			 	echo generateTable($paginator->getCurrentItems(),$this->header,$pathToController);
			}
			else
			{
				echo "<div id='noRecords'>".$this->translate('No records found')." <br/></div>";
			}
		?>
	</form>  
	</div> 