 <div class="completeText" id="application_controlBar">
 	<?php if ($this->pageCount): ?>
	<div id="paginationControl">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
	<a href="<?php echo $this->url(array('cpage' => $this->previous)); ?>">&lt; <?php echo $this->translate("Previous");?></a> <?php else: ?>
	<span class="disabled">&lt; <?php echo $this->translate("Previous");?></span> |
	<?php endif; ?>
	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
	<a href="<?php echo $this->url(array('cpage' => $page)); ?>"><?php echo $page; ?></a> |
	<?php else: ?>
	<?php echo $page; ?> |
	<?php endif; ?>
	<?php endforeach; ?>
	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	<a href="<?php echo $this->url(array('cpage' => $this->next)); ?>"><?php echo $this->translate("Next");?> &gt;</a>
	<?php else: ?>
	<span class="disabled"><?php echo $this->translate("Next");?> &gt;</span>
	<?php endif; ?>
	</div>
	<?php endif; ?>
	
 </div>
