<br /><br />
<div align="center"><font><?php echo $this->translate('Content Activity Report');?></font></div>
<div id="noRecords" align="center">
<?php echo $this->translate('Please purchase the')?> <a href='http://www.precurio.com/commercial-services-report.php' target='_blank'><?php echo $this->translate('report bundle')?></a> <?php echo $this->translate('to access this report')?> <br/> 
</div>
		 
<br/><br/>