<?php 

require_once('visitor/models/Appointments.php'); 
require_once('visitor/models/vo/Appointment.php'); 
$is_receptionist = VisitorUtil::isReceptionist($this->user->id);
?>
<?php 

$appointments = new Appointments();
$type = $this->type;
$mine = ! Precurio_Utils::isNull($this->mine);

$page =  1;
$rowsPerPage = 10;



if (isset($this->page)) {
  $page = $this->page;
}

$firstRec = ($page-1)*$rowsPerPage + 1  ;

$rsAppointments = ( ! Precurio_Utils::isNull($this->mine) ) ? $appointments->getAppointmentSummary($type, $page, true) : $appointments->getAppointmentSummary($type, $page);
$total = ( ! Precurio_Utils::isNull($this->mine) ) ? $appointments->getCount($type, true) : $appointments->getCount($type);
$rowCount = 0;

//echo $rsAppointments;
$totalRows_rsAppointments = count($rsAppointments);

switch($type)
{
	case Appointments::UPCOMING:
		$title = $this->translate('Upcoming Appointments');
		$emptyMsg = ( ! Precurio_Utils::isNull($this->mine) ) ? $this->translate('You have no upcoming appointment'): $this->translate('There are no upcoming appointments');
		$selected = 'upcoming';		
		break;
	case Appointments::PAST:
		$title = $this->translate('Past Appointments');
		$emptyMsg = ( ! Precurio_Utils::isNull($this->mine) ) ? $this->translate('You have not had any appointment in the past'): $this->translate('There are no past appointments');
		$selected = 'past';
		break;
	case Appointments::CURRENT:
		$title = $this->translate("Today's Appointments");
		$emptyMsg = $this->translate('No appointment has been scheduled for today');
		$selected = 'current';
		break;
}

$relative = "/visitor/list/{$selected}appointment/";
//if($mine) $relative.='mine/1/';
$relative.='mine/1/'
?>

<div  id="tab" class="appTabs">
<?php require_once('visitor/views/scripts/tabs.phtml');?>
<span class="listHeader"> <?php echo $title; ?>  
</span> 
<?php if($total):?><span class="textLinks"> Showing <?php 
 echo ($firstRec);?>  to  <?php echo ($firstRec + $totalRows_rsAppointments - 1) ;?> of <?php echo  $total;?> </span><?php endif;?>
   
 <?php
  if( $is_receptionist ) 
  {
  ?>
   
<?php if($type == Appointments::UPCOMING) { ?>
<!--<span> <?php if($mine) echo '('. $this->translate('Yours') . ')' ; else echo '('. $this->translate('All') . ')' ; ?> </span>-->
<span id='a' style="display:none"> <?php if($mine) echo '0'; else echo '1'; ?> </span>
<!--<a id='upcomingchecker' href='#'> <?php if($mine) echo 'Click to fetch all upcoming appointments'; else echo 'Click to fetch all your upcoming appointments'; ?>   	 	
	
	</a>-->
<?php } ?>
<?php if($type == Appointments::PAST) { ?>
<!--<span> <?php if($mine) echo '('. $this->translate('Yours') . ')' ; else echo '('. $this->translate('All') . ')' ; ?></span>
--><span id='a' style="display:none"> <?php if($mine) echo '0'; else echo '1'; ?> </span>
<!--<a id='pastchecker' href='#'> <?php if($mine) echo 'Click to fetch all past appointments'; else echo 'Click to fetch all your past appointments'; ?>   	 	
	
	</a>-->
<?php } ?>

<?php
    }
    ?>

 <div  id="visitors_body"> 
 
	<div class="contentPad">

      <?php  
								
			//confirm that there are records, otherwise , display message
			if ($totalRows_rsAppointments > 0)
			{
		?>
                                
                                
         <div class="tableHeader">
                <div class="leftside" >
                      <div class="rightPadding">
                                <a href="#"> <?php echo $this->translate('Title'); ?>
                        </a></div>
                 </div>
                                      
                                      
				<div class="leftside" >
                       <div class="rightPadding">
                              <?php echo $this->translate('Host'); ?>
                        </div>
				</div>
				
				<div class="leftside" >
                       <div class="rightPadding">
                             <?php echo $this->translate('Appointment Date') ?>
                        </div>
				</div>
				
				
         </div>  
		 
		  <?php 
			while ($rowCount < $rowsPerPage && isset($rsAppointments[$rowCount])):
			$row_rsAppointments = $rsAppointments[$rowCount];
			
			//echo $row_rsAppointments['full_name'];
		?>
							
									<!-- start table body -->  
                              <div tag="<?php echo $type; ?>"  id="<?php echo ($row_rsAppointments['id']); ?>" class="tableBody appointmentLine <?php if ($rowCount % 2 == 0) echo ("even"); ?>">
                               	<div class="leftside" >
                               		<div class="rightPadding" >
                                       	<a href="#" ><?php echo ($row_rsAppointments['title']); ?>
                                    </a></div>
                                </div>
                                      
                                      
                                      
                                      <div class="leftside" >
                                		<div class="rightPadding">
                                        	<?php echo $row_rsAppointments->getHost(); ?>
                                        </div>
                                      </div>
                            
								<div class="leftside" >
                                		<div class="rightPadding">
                                        	<?php echo ( $type != Appointments::CURRENT ) ? $row_rsAppointments->getAppointmentDate() : '' ; ?> <?php echo '('.$row_rsAppointments->getAppointmentTime().')'; ?>
                                        </div>
                                      </div>
									  
								
							</div>
							
							                            <!-- end table body -->
									
									<?php $rowCount++; endwhile; ?>
									
									</div>
						</div>
						
						<div id="pager" class="buttons">
                         <?php
						 //paging script 
						 
						 $maxPage = ceil($total/$rowsPerPage);
						
						// print the link to access each page
						//$self = $_SERVER['PHP_SELF'];
						$nav  = '';
						$currentpage = $page ; 
						
						$startpager = 1 ;
						
						$pagerTotal = $maxPage; 
						$showfirst = false;
						$showlast = false;
						if ($maxPage > 5 )
						{
							$pagerTotal = 5 ; 
							$startpager = $currentpage - 2; 
							$showfirst = true;
							$showlast = true;
							if ($currentpage < 3)
							{
								$startpager = 1;
								$showfirst = false;
							}						
							
							if ($maxPage - $currentpage < 3 )
							{
								$startpager = $maxPage - 4; 
								$showfirst = true;
								$showlast = false;
							}
							
							if ($maxPage - $currentpage < 5 )
							{
								$showlast = false;
							}
						}
						
						
						$count = 1; 
					 
						
					    
						for($page = $startpager; $count <= $pagerTotal; $page++)
						
						{
						   
						   
						   if ($page == $currentpage)
						   {
							  $nav .= "<span> $page </span> "; // no need to create a link to current page, create span instead
						   }
						   else
						   {
							  $nav .= " <a href=\"#$page\" id=\"$type\" rel=\"$page\">$page</a> ";
						   }
						   $count++;
						}
						 
						if ($currentpage > 1 and $showfirst)
						{
						   $page  = $currentpage - 1;
						
							$next = '&nbsp;';//
						   $prev  = '&nbsp;';
						   $first = " <a href=\"#$page\" id=\"$type\" rel=\"1\">First</a> ";
						}
						else
						{
							$next = '&nbsp;';
						   $prev  = '&nbsp;'; // we're on page one, don't print previous link
						   $first = '&nbsp;'; // nor the first page link
						}
						
						if ($currentpage < $maxPage and $showlast)
						{
						   $page = $currentpage + 1;
						   $next = '&nbsp;';//
						   $prev  = '&nbsp;';
						
						   $last = " <a href=\"#$page\" id=\"$type\" rel=\"$maxPage\">Last</a> ";
						}
						else
						{
						   $next = '&nbsp;'; // we're on the last page, don't print next link
						   $last = '&nbsp;'; // nor the last page link
						}
						
						// print the navigation link
						echo $first . $prev . $nav . $next . $last;


						 ?>
                       
                        </div>

				<?php		}
								else
								{
								
								 ?>
                               <div id="noRecords">
                              <?php 
				 echo $emptyMsg;
			      ?> <br />
                              
                                 
                               <?php
								 }
								 ?>			
                                     
      
	</div>
 </div>
 

<script type='text/javascript'>

$('.appointmentLine').click( function() {
		
	    page =  '<?php echo $this->baseUrl();?>/visitor/appointment/view/id/' + ($(this).attr("id"))+ '/type/' + $(this).attr("tag");
	    page+= '<?php if ( ! Precurio_Utils::isNull($this->mine) ) echo '/mine/1'; ?>'
	    //alert(page);
	    //return false;
		
		$("#loading").show();
		
		loadPage(page);
	
		return false;
	});
	
$('#pager a').click(function()  {
		$(this).css('outline','none');
		
		
		var page  = "<?php echo $this->baseUrl().$relative?>page/" + $(this).attr("rel");
	
		$("#loading").show();
	//	$("#contacts_b").hide('slow');
		loadPage(page);
     	
		
		
	
		return false;
		
		
		
	}); 
</script>
