<?php 

require_once('visitor/models/Visitors.php'); 
require_once('visitor/models/vo/Visitor.php'); 
require_once('visitor/models/VisitorStrings.php');
?>

<?php 

$visitors = new Visitors();
//$type = $this->type;

$page =  1;
$rowsPerPage = 10;
$mine = ! Precurio_Utils::isNull($this->mine);


if (isset($this->page)) {
  $page = $this->page;
}

$firstRec = ($page-1)*$rowsPerPage + 1  ;


$total = ( ! Precurio_Utils::isNull($this->mine) ) ? $visitors->getCount(true) : $visitors->getCount();
$rowCount = 0;
$rsVisitors = ( ! Precurio_Utils::isNull($this->mine) ) ? $visitors->getVisitorSummary($page, true) : $visitors->getVisitorSummary($page);
//echo $rsVisitors;
$totalRows_rsVisitors = count($rsVisitors);

$type = ( ! Precurio_Utils::isNull($this->mine) ) ? VisitorStrings::USER : VisitorStrings::RECEPTIONIST;
?>

<div id="holder" >
	
    <div class="rightside">
	<!--<form>
    	<input type="text" id="who"  class="searchBox"/>    
		</form>-->
    </div>
</div>

<?php //$selected = 'past'; ?>
<div  id="tab" class="appTabs">
<?php 

if( VisitorUtil::isReceptionist($this->user->id) )
require_once('visitor/views/scripts/index/tabs.phtml');
?>

<span class="listHeader"> <?php echo $this->translate('Visitors'); ?>  </span> <?php if($total):?><span class="textLinks"> Showing <?php 
 echo ($firstRec);?>  to  <?php echo ($firstRec + $totalRows_rsVisitors - 1) ;?> of <?php echo  $total;?> </span><?php endif;?>
   
 <?php
  if( VisitorUtil::isReceptionist($this->user->id) ) 
  {
  ?>
   

<span id='a'> <?php if($mine) echo '(Yours)'; else echo '(All)'; ?> </span>
<a id='checker' href='#'> <?php if($mine) echo 'Click to fetch all visitors logged in by you'; else echo 'Click to fetch all your visitors'; ?>   	 	
	
	</a>


<?php } ?>
				
							
							
                      		
                              <!--    <a href="/visitor/index/search" id='searchVisitor' style="float:right" class="positive">
			                     <img src="/library/css//images/icons/tick.png" alt=""/> 
			                      Search    </a> -->
 <div  id="visitors_body"> 
 
	<div class="contentPad">

      <?php  
								
			//confirm that there are records, otherwise , display message
			if ($totalRows_rsVisitors > 0)
			{
		?>
                                
                                
         <div class="tableHeader">
                <div class="leftside" >
                      <div class="rightPadding">
                                <a href="#"> <?php echo $this->translate("Visitor's Name") ?>
                        </a></div>
                 </div>
                                      
                        
		 </div>  
		 
		 <?php 
			while ($rowCount < $rowsPerPage && isset($rsVisitors[$rowCount])):
			$row_rsVisitors = $rsVisitors[$rowCount];
			
			//echo $row_rsAppointments['full_name'];
		?>
							
									<!-- start table body -->  
                              <div tag="<?php echo $type; ?>"  id="<?php echo ($row_rsVisitors['id']); ?>" class="tableBody visitorLine <?php if ($rowCount % 2 == 0) echo ("even"); ?>">
                               	<div class="leftside"  style="width: 300px" >
                               		<div class="rightPadding" >
                                       	<a href="#" >
					<?php 
					echo ($row_rsVisitors['full_name']);
					if( $mine &&  $row_rsVisitors->isExpected() )
					{
						$visits = $row_rsVisitors->getVisits();
					}
					echo '<font style="font-style: italic; "> '.$row_rsVisitors->getExpectedTime().'</font>';
					?>
                                    </a></div>
                                </div>
				
				                                      
								<div class="rightside" >
                                		<div class="rightPadding">
                                        	<a href='#'> <?php echo $this->translate('view history') ?></a>
                                        </div>
                                      </div>
				      
				      
									  
								
							</div>
							
							                            <!-- end table body -->
									
									<?php $rowCount++; endwhile; ?>
									
									</div>
						</div>
						
						  <div id="pager" class="buttons">
                         <?php
						 //paging script 
						 
						 $maxPage = ceil($total/$rowsPerPage);
						
						// print the link to access each page
						//$self = $_SERVER['PHP_SELF'];
						$nav  = '';
						$currentpage = $page ; 
						
						$startpager = 1 ;
						
						$pagerTotal = $maxPage; 
						$showfirst = false;
						$showlast = false;
						if ($maxPage > 5 )
						{
							$pagerTotal = 5 ; 
							$startpager = $currentpage - 2; 
							$showfirst = true;
							$showlast = true;
							if ($currentpage < 3)
							{
								$startpager = 1;
								$showfirst = false;
							}						
							
							if ($maxPage - $currentpage < 3 )
							{
								$startpager = $maxPage - 4; 
								$showfirst = true;
								$showlast = false;
							}
							
							if ($maxPage - $currentpage < 5 )
							{
								$showlast = false;
							}
						}
						
						
						$count = 1; 
					 
						
					    
						for($page = $startpager; $count <= $pagerTotal; $page++)
						
						{
						   
						   
						   if ($page == $currentpage)
						   {
							  $nav .= "<span> $page </span> "; // no need to create a link to current page, create span instead
						   }
						   else
						   {
							  $nav .= " <a href=\"#$page\" id=\"$type\" rel=\"$page\">$page</a> ";
						   }
						   $count++;
						}
						 
						if ($currentpage > 1 and $showfirst)
						{
						   $page  = $currentpage - 1;
						
							$next = '&nbsp;';//
						   $prev  = '&nbsp;';
						   $first = " <a href=\"#$page\" id=\"$type\" rel=\"1\">First</a> ";
						}
						else
						{
							$next = '&nbsp;';
						   $prev  = '&nbsp;'; // we're on page one, don't print previous link
						   $first = '&nbsp;'; // nor the first page link
						}
						
						if ($currentpage < $maxPage and $showlast)
						{
						   $page = $currentpage + 1;
						   $next = '&nbsp;';//
						   $prev  = '&nbsp;';
						
						   $last = " <a href=\"#$page\" id=\"$type\" rel=\"$maxPage\">Last</a> ";
						}
						else
						{
						   $next = '&nbsp;'; // we're on the last page, don't print next link
						   $last = '&nbsp;'; // nor the last page link
						}
						
						// print the navigation link
						echo $first . $prev . $nav . $next . $last;


						 ?>
                       
                        </div>

				<?php		}
								else
								{
								
								 ?>
                               <div id="noRecords">
                              <?php echo $this->translate('You have no visitor records') ?>. <br />
                              
                                 
                               <?php
								 }
								 ?>			
                                     
      
	</div>
 </div>
 
 </div>
 
 <script type='text/javascript'>
 $('#pager a').live('click', function()  {
		$(this).css('outline','none');
		
		//alert ("test");
		
		var page  = "<?php echo $this->baseUrl();?>/visitor/list/visitor/page/" + $(this).attr("rel");
		page+= '<?php if ( $mine ) echo '/mine/1'; ?>'
	
		$("#loading").show();
	//	$("#contacts_b").hide('slow');
		loadPage(page);
     	
		
		
	
		return false;
		
		
		
	}); 
 </script>
 
	

