<?php $links = $this->contentView()->getCompanyLinks();?>
<?php if(count($links) == 0) {
 echo '<div id="noRecords">'. $this->translate("No available company links").'.</div>';
 return;
}?>
         <?php foreach($links as $link):?>
             <a href="<?php echo $link->url; ?>" target="<?php echo $link->target; ?>">
             <img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/bullet_feed.png" width="16" height="16" />
             <?php echo $link->title; ?>
             </a>
             <br /> <br />
           <?php endforeach;?>