	<?php 
	$pathToController = $this->pathToController;

	require_once 'Zend/Paginator.php';
	$paginator = Zend_Paginator::factory($this->list);
	$paginator->setCurrentPageNumber($this->cpage);
	$paginator->setItemCountPerPage(10);
	$this->paginator = $paginator;
	?>
	
	<form method="post" name="searchListForm" id="searchListForm" action="<?php echo $pathToController."index" ?> ">
		<input id="table" name="table" value="<?php echo $this->table;?>" type="hidden">
		<table class="ewBasicSearch">
			<tbody><tr>
				<td>
					<input name="search" id="search" size="20" value="<?php echo $this->searchText;?>" type="text">
					<input name="Submit" id="Submit" value="<?php echo $this->translate("Search");?> (*)" type="Submit">&nbsp;
					<a href="<?php echo $this->pathToController;?>"><?php echo $this->translate("Show all");?></a>&nbsp;
				</td>
			</tr>
			</tbody>
		</table>
	</form>
	<span id="adminList">
		<div class="buttons">
		
<?php if(Precurio_Session::getLicense()->isPro):?>
		<a href="<?php echo $this->baseUrl()."/formsbuilder/index.php?userid=".Precurio_Session::getCurrentUserId(); ?>" class="mild" ><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/add.png" alt=""/>  <?php echo $this->translate("Build New Workflow");?></a>&nbsp;&nbsp;
<?php else:?>
		<a href="http://www.precurio.com/commercial-services-workflow.php" class="mild" target="_blank"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/add.png" alt=""/>  <?php echo $this->translate("Build New Workflow");?></a>&nbsp;&nbsp;
<?php endif;?>
		<a href="" onclick="if (!keySelected(document.listForm)) alert('<?php echo $this->translate("No records selected");?>'); else {document.listForm.action='<?php echo $pathToController."delete" ?>';document.listForm.submit();};return false;" class="mild"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/delete.png" alt=""/>  <?php echo $this->translate("Delete Selected Workflows");?></a>&nbsp;&nbsp;
		
		</div>
	</span>
	<br />  
<br /> 
	<div id="adminTable"> 
	
	<?php echo $this->paginationControl($this->paginator, 'Elastic'); ?>
	<form action="" name="listForm" id="listForm" method="post"> 
		<?php 
			if($paginator->getCurrentItemCount())
			{
			 	echo Precurio_Utils::array2Table($paginator->getCurrentItems(),$this->header,$pathToController);
			}
			else
			{
				echo "<div id='noRecords'>".$this->translate('No have no workflows installed')." <br/> <a href='http://www.precurio.com' target='_blank'>".$this->translate('Click here to buy workflows')."</a> </div>";
			}
		?>
	</form>  
	</div>