<?php
	require_once('forum/models/Forums.php');
	
	$forum = Forums::getForum($this->forum_id);
?>

<script type="text/javascript">
    _editor_url  = "<?php echo $this->baseUrl();?>/library/xinha/";  // (preferably absolute) URL (including trailing slash) where Xinha is installed
    _editor_lang = "en";      // And the language we need to use in the editor.
    _editor_skin = "silva";   // If you want use a skin, add the name (of the folder) here
  </script>
  
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/xinha/XinhaCore.js"></script>


<script type="text/javascript">
xinha_editors = null;
xinha_init    = null;
xinha_config  = null;
xinha_plugins = null;
xinha_init = xinha_init ? xinha_init : function()
{
	xinha_editors = xinha_editors ? xinha_editors :
		  [
		    'contentBody'
		  ];
	xinha_plugins = xinha_plugins ? xinha_plugins :
		  [
		   'ContextMenu',
		   'TableOperations'
		  ];
	 if(!Xinha.loadPlugins(xinha_plugins, xinha_init)) return;
	 
	 xinha_config = xinha_config ? xinha_config() : new Xinha.Config();
	   
	  //this is the standard toolbar, feel free to remove buttons as you like
	  xinha_config.toolbar =
	  [
	    ["popupeditor"],
	    ["separator","formatblock","fontname","fontsize","bold","italic","underline","strikethrough"],
	    ["separator","forecolor","hilitecolor","textindicator"],
	    ["separator","subscript","superscript"],
	    ["linebreak","separator","justifyleft","justifycenter","justifyright","justifyfull"],
	    ["separator","insertorderedlist","insertunorderedlist","outdent","indent"],
	    ["separator","inserthorizontalrule","createlink","insertimage","inserttable"],
	    ["linebreak","separator","undo","redo","selectall","print"], (Xinha.is_gecko ? [] : ["cut","copy","paste","overwrite","saveas"]),
	    ["separator","killword","clearfonts","removeformat","toggleborders","splitblock","lefttoright", "righttoleft"],
	    ["separator","htmlmode","showhelp","about"]
	  ];
		 
	  xinha_config.pageStyleSheets = [ _editor_url + "examples/files/full_example.css" ];
		  
	  xinha_editors   = Xinha.makeEditors(xinha_editors, xinha_config, xinha_plugins);
	  Xinha.startEditors(xinha_editors);
}

	Xinha._addEvent(window,'load', xinha_init); // this executes the xinha_init function on page load 
			
</script>



<script type='text/javascript'>
$().ready(function()
{
	xinha_init();
});
</script>

<style>
	.htmlarea{border:1px solid white}
</style>
<script type='text/javascript'>

$('#saveTopic').live('click', function()  
{	
	var editor = xinha_editors["contentBody"];
	var content = editor.getEditorContent();
	
	$.post("<?php echo $this->baseUrl();?>/forum/topic/submit", {title: $('#t_title').val(), post: content, forum_id: <?php echo $this->forum_id ?>},
	function(data)
	{
		alert(data);
		location.reload();
	}, "text");
});
</script>

<div  class="titleWindow "> 
	<div id="titleText">
    	<span> <?php echo $this->translate('Forum Topic'); ?>:</span> <?php echo $forum->getTitle(); ?>
	</div>
</div>
<div>
<table class="popup_table" cellspacing='0' cellpadding='10' width="300px">
			<tr>	
				<td>
					<div class="post-author">
					  <label><?php echo $this->translate('Topic'); ?></label></div>
				</td>
				
				<td class="alt"><input id="t_title" type="text"/></td>
				
			</tr>
			
			<tr>	
				<td valign="top">
                	<label><?php echo $this->translate('Post'); ?></label>
				</td>
				
				<td class="alt">
					<div class="post_body">
                        <div>
                            <textarea rows="7"  id="contentBody" name="body" style="width:600px"> </textarea>
                        </div>
                    </div>
				</td>
			
			</tr>
			
			<tr>
			  <td>&nbsp;</td>
			  <td class="alt"><div id="saveTopic" class="buttons"><a href="javascript:void(0)">
			  <img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/tick.png" alt=""/> 
			  <?php echo $this->translate('Create Topic'); ?></a></div></td>
  </tr>
			
			</table>
	</div>