<div class="dashboardLine">
        	<div class="dashboardModule">
            	<img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->userView()->getUserThemeStyle(); ?>/images/icons/calendar.png"  /><a href="#"><?php echo $this->translate("Events");?>            </a>
             </div>
             <div class="dashboardContent">
             	 <div id="dashEventsDesc">
   	 	  <span class="nameText"><a href="<?php echo $this->baseUrl();?>/event/upcoming/details/e_id/<?php echo $this->model->getId();?>" ><?php echo $this->model->getTitle();?> </a></span><br />
                <?php echo $this->model->getSummary();?>
                <p>
                <?php echo $this->translate("Venue");?> : <?php echo $this->model->venue;?>
                </p>
                <p><a href="<?php echo $this->baseUrl();?>/event/upcoming/details/e_id/<?php echo $this->model->getId();?>"><?php echo $this->translate("View Event Details");?></a> </p>
           </div>
             </div>
        </div>