<div class="dashboardLine">
        	<div class="dashboardModule">
            	<img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->userView()->getUserThemeStyle();?>/images/icons/discuss.png"  /><a href="#"><?php echo $this->translate("Status");?>         </a>
             </div>
             <div class="dashboardContent">
             	 <div id="dashEventsDesc">
   	 	  <span class="nameText"><?php echo $this->model->getFullName();?></span> <?php echo $this->model->getMessage();?> 
                
               
           </div>
             </div>
        </div>