
<?php 

require_once('contact/models/Contacts.php'); 
require_once('contact/models/vo/Contact.php'); 
?>

<?php 

$contacts = new Contacts();
$type = $this->type;

$page =  1;
$rowsPerPage = 10;



if (isset($this->page)) {
  $page = $this->page;
}

$firstRec = ($page-1)*$rowsPerPage + 1  ;

switch ($type)
{
	case Contacts::TYPE_ALL:
		$desc = $this->translate("All Contacts");
		break;
	case Contacts::TYPE_MY:
		$desc = $this->translate("My Contacts");
		break;
	case Contacts::TYPE_SHARED:
		$desc = $this->translate("Shared Contacts");
		break;
	case Contacts::TYPE_CO:
		$desc = $this->translate("Coworkers");
		break;
}
$total = $contacts->getCount($type);
$rowCount = 0;
$rsContacts = $contacts->getContactSummary($type, $page);
$totalRows_rsContacts = count($rsContacts);

?>
<div id="contactsHolder">
 <span class="listHeader"> <?php echo ($desc) ?>  </span> <?php if($total):?><span class="textLinks"> <?php echo $this->translate("Showing");?> <?php 
 echo ($firstRec);?>  <?php echo $this->translate("to");?>  <?php echo ($firstRec + $totalRows_rsContacts - 1) ;?> <?php echo $this->translate("of");?> <?php echo  $total;?> </span><?php endif;?>

               			<div id="contacts_body">
                       	  <div class="contentPad">
                            
                            	<?php  
								
								//confirm that there are records, otherwise , display message
								if ($totalRows_rsContacts > 0)
								{
								?>
                                
                                
                                <div class="tableHeader">
                                	<div class="leftside" >
                                		<div class="rightPadding">
                                        	<a href="#"><?php echo $this->translate("Full Name");?>
                                        </a></div>
                                  </div>
                                      
                                      
                                      
                                      <div class="leftside" >
                                		<div class="rightPadding">
                                        	<?php echo $this->translate("Phone Numbers");?>
                                        </div>
                                      </div>
                                </div>
                                
                                <?php 
								while ($rowCount < $rowsPerPage && isset($rsContacts[$rowCount])):
								$row_rsContacts = $rsContacts[$rowCount]
									?>
							
									<!-- start table body -->  
                              <div tag="<?php echo ($type == Contacts::TYPE_ALL ? (isset($row_rsContacts['first_name']) ? Contacts::TYPE_CO : Contacts::TYPE_SHARED ) : $type); ?>"  id="<?php echo ($row_rsContacts['id']); ?>" class="tableBody <?php if ($rowCount % 2 == 0) echo ("even"); ?>">
                               	<div class="leftside" >
                               		<div class="rightPadding" >
                                       	<a href="#" ><?php echo ($row_rsContacts['full_name']); ?>
                                    </a></div>
                                </div>
                                      
                                      
                                      
                                      <div class="leftside" >
                                		<div class="rightPadding">
                                        	<?php echo ($row_rsContacts['mobile_phone']); ?>
                                        </div>
                                      </div>
                            </div>
                            <!-- end table body -->
                                
                              
                            
                              <?php $rowCount++; endwhile; ?>
							  
&nbsp;						
                            </div>
                        </div> 
                        
                        <div id="pager" class="buttons">
                         <?php
						 //paging script 
						 
						 $maxPage = ceil($total/$rowsPerPage);
						
						// print the link to access each page
						//$self = $_SERVER['PHP_SELF'];
						$nav  = '';
						$currentpage = $page ; 
						
						$startpager = 1 ;
						
						$pagerTotal = $maxPage; 
						$showfirst = false;
						$showlast = false;
						if ($maxPage > 5 )
						{
							$pagerTotal = 5 ; 
							$startpager = $currentpage - 2; 
							$showfirst = true;
							$showlast = true;
							if ($currentpage < 3)
							{
								$startpager = 1;
								$showfirst = false;
							}						
							
							if ($maxPage - $currentpage < 3 )
							{
								$startpager = $maxPage - 4; 
								$showfirst = true;
								$showlast = false;
							}
							
							if ($maxPage - $currentpage < 5 )
							{
								$showlast = false;
							}
						}
						
						
						$count = 1; 
					 
						
					    
						for($page = $startpager; $count <= $pagerTotal; $page++)
						
						{
						   
						   
						   if ($page == $currentpage)
						   {
							  $nav .= "<span> $page </span> "; // no need to create a link to current page, create span instead
						   }
						   else
						   {
							  $nav .= " <a href=\"#$page\" id=\"$type\" rel=\"$page\">$page</a> ";
						   }
						   $count++;
						}
						 
						if ($currentpage > 1 and $showfirst)
						{
						   $page  = $currentpage - 1;
						
							$next = '&nbsp;';//
						   $prev  = '&nbsp;';
						   $first = " <a href=\"#$page\" id=\"$type\" rel=\"1\">".$this->translate("First")."</a> ";
						}
						else
						{
							$next = '&nbsp;';
						   $prev  = '&nbsp;'; // we're on page one, don't print previous link
						   $first = '&nbsp;'; // nor the first page link
						}
						
						if ($currentpage < $maxPage and $showlast)
						{
						   $page = $currentpage + 1;
						   $next = '&nbsp;';//
						   $prev  = '&nbsp;';
						
						   $last = " <a href=\"#$page\" id=\"$type\" rel=\"$maxPage\">".$this->translate("Last")."</a> ";
						}
						else
						{
						   $next = '&nbsp;'; // we're on the last page, don't print next link
						   $last = '&nbsp;'; // nor the last page link
						}
						
						// print the navigation link
						echo $first . $prev . $nav . $next . $last;


						 ?>
                       
                        </div>
                        <?php		}
								else
								{
								
								 ?>
                               <div id="noRecords">
                               <?php echo $this->translate("You have no contacts in this category");?>. <br />
                              
                                 
                               <?php
								 }
								 ?>
                     
</div>   