<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->company_name; ?> <?php echo $this->translate("Intranet");?>::<?php echo $this->translate('login');?></title>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/js/jquery/jquery.js"></script>
<?php 
echo ($this->headScript());
echo ($this->headLink());
?>
<!--[if lte IE 7]> <link href="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->theme;?>/theme_ie6.css" rel="stylesheet" type="text/css" /> <![endif]-->

 <script type="text/javascript">
	$(document).ready(function(){
		$('.clearField').autofill({
					value: 'Username'
				});
		
	});	
</script>
</head>

<body>


<div id="headerGradient">

  <div id="information_container" >
  	<div id="logoPlaceHolder" >
     <a href="<?php echo $this->baseUrl();?>/"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/logo.jpg" /></a>
    </div>	
</div>
</div>
<div id="headerBottom">

</div>
<?php echo $this->layout()->content;?>
	
<div id="lowerGradient">
	<div id="homeContainer">
   	  <div id="home_left">
        	<div id="newsBox" class="box_A" >  
            	<div class="contentPad" >
            		<strong> <?php echo Precurio_Date::getGreeting();?></strong> - <?php echo (Precurio_Date::now()->get(Precurio_Date::DATE_LONG));?>  
                    <?php echo $this->contentView()->getPromotionalArticle();?>
           	   	</div>
               
               
        	</div>
            <div id="newsBox_Latest" class="box_B topMargin " >	   
            	<div class="contentPad">
	                <span class="header"> <?php echo $this->translate("Latest News");?></span><br/>
	                <?php $recentNews = $this->newsView()->getRecent(3);
	                if(count($recentNews) > 1):?>
		         	<?php foreach($recentNews as $news):?>
		             <a href="<?php echo $this->baseUrl();?>/news/view/details/c_id/<?php echo $news->getContentId(); ?>"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/bullet_feed.png" width="16" height="16" /><?php echo $news->getShortHeadline(); ?></a><br />
		             <span class="textLinks"><?php echo $news->getDateAdded(); ?></span><br/>
		           <?php endforeach;?>
		           <?php else:?>
		          	 <div id="noRecords">
                               <?php echo $this->translate("No recent news");?><br />
                               </div>
                   <?php endif;?>
                </div>
        	</div>
        	
      </div>
      
      <div id="home_right">
      		<?php echo $this->contentView()->getWelcomeAdvert(); ?>
      
   		<div id="loginFormBox">
        	<div id="loginformbox_left">
        		
               
                 <form action= '<?php echo $this->baseUrl()?>/login/submit' method='post'>
				  <span> <strong><?php echo($this->translate('Login to the portal'))?> </strong></span><br /><span class="invalid"><?php echo ($this->loginError)?> </span><br /><br />
                 
                     <input name="username" type="text" id="username" class="clearField" /> 
                
                    <input name="password" type="password" id="password"  />
                   
                    <input type="submit" name="submit" id="submit" value="<?php echo($this->translate('Submit'))?>" />
                    <br />
                    <br />
<!--                    <input type="checkbox" id="autoSignIn"  name="autoSignIn"  style="margin-right:0px"/>-->
                    <?php // echo($this->translate('Keep me signed in automatically.'))?>
                    <br />
                    <br />
                    <!--<a href="#" class="forgotText"> <?php echo($this->translate('Forgot password?'))?> </a>
                    
                    
                --></form>
           </div>
           <div id="loginformbox_right">
              	
           </div>
        </div>
              
        <div id="product_bar" >
              <?php echo $this->contentView()->getSlidingAdverts(); ?>
        </div>
              
              
        <div id="home_down">
        	<div  id="discuss_learn_share" class="box_C ">
				<div id="discussBox_right"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/share_large.jpg" width="68" height="57" /></div>
            	<div class="contentPad" id="discussBox">
                	<span class="boldText" > <?php echo $this->translate("Share");?></span> 
                    <br />
                    <br />
                    <?php echo($this->translate('Be more effective in your daily work by collaborating with peers.'))?>
		            
            	</div>            
        	</div>
            
            <div  id="discuss_learn_share" class="box_C rightMargin">
                <div id="discussBox_right"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/learn_large.jpg" width="54" height="57" /></div>
                         <div class="contentPad" id="discussBox">
                                    <span class="boldText" > <?php echo $this->translate("Learn");?> </span> 
                                    <br />
                                    <br />
                        <?php echo($this->translate('Learn about the company, staffs, policies, and events .'))?>            
                      	</div>            
            </div>
            
            <div  id="discuss_learn_share" class="box_C rightMargin">
            	<div id="discussBox_right"><img src="<?php echo $this->baseUrl();?>/library/css/<?php echo $this->themestyle;?>/images/icons/discuss_large.jpg" width="47" height="57" />                </div>
            	<div class="contentPad" id="discussBox">
                	<span class="boldText" > <?php echo $this->translate("Discuss");?> </span> 
                    <br />
                    <br />
                  <?php echo($this->translate('Discuss ideas and challenges with like minded people. '))?>
                             	</div>
          </div>
        </div>
        
      </div>
   	
      
    </div>
</div>

</body>
</html>
