<?php
/**
 * Default Layout
 *  
 * @author Klein Devort
 * @version 2
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
?>
<html>

  <?php require_once('header.phtml'); ?>
  <!-- Container -->
  <div id="container">
  	<!-- Left Bar -->
	<div id="left_bar">
  		<?php require_once('sidebar_a.phtml'); ?>
  	</div>
  	<!-- End Left Bar -->
  	
	<div id="app_bar">
		<div class="box_D rounded">
			<div class="appPad">
				<?php require_once('nav.phtml'); ?>
				<?php echo $this->layout()->content ?>
			</div>
		</div>
	</div>
	
	<!-- right Bar -->
	<div id="right_bar"> 
	
	</div>
	<!-- End right Bar -->

  </div><!-- End Container -->
<?php require_once 'footer.phtml';?>

</html>