<?php

/**
 * Admin Layout
 *  
 * @author Klein Devort
 * @version 2
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

?>

<html>

  <?php require_once('header.phtml'); ?>
  <!-- Container -->
  <div id="container">
  	

	
	<div id="app_bar">
		<div class="box_D rounded">
			<div >
				
				<div class="box_head">
					<h1><?php 	echo $this->pageTitle; ?></h1> 
				</div>
				<div id="navHolder">
			<?php require_once('nav.phtml'); ?>
		</div>
				<div class="appPad">
					<?php echo $this->layout()->content ?>
				</div>
			</div>
		</div>
	</div>
	
	<!-- Left Bar -->
	<div id="left_bar">
  		<?php require_once('sidebar_a.phtml'); ?>
  	</div>
  	<!-- End Left Bar -->
  	
	<!-- right Bar -->
	<div id="right_bar"> 
	
	</div>
	<!-- End right Bar -->

  </div><!-- End Container -->
<?php require_once 'footer.phtml';?>
</html>