<?php
/**
 * Default Layout
 *  
 * @author Klein Devort
 * @version 2
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

echo ($this->headScript());
echo ($this->headLink());
?>

<html>

 
  <!-- Container -->
  <div id="err_container">
  	
  	
	<div id="app_bar">
		<div class="box_D rounded">
			<div >
				<?php //require_once('nav.phtml'); ?>
				<div class="box_head">
					<h1>Error</h1>
				</div>
				<div class="appPad">
					  <?php echo $this->layout()->content ?>
				</div>
			</div>
		</div>
	</div>
	
	<!-- Left Bar -->
	
  	<!-- End Left Bar -->
	

  </div><!-- End Container -->


</html>