<head>
	<title><?php echo $this->company_name; ?>  <?php echo $this->translate("Intranet");?></title>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/js/jquery/jquery.js"></script>
	
	<?php echo $this->headLink();?>

</head>
<?php $selected = $this->page;?>
<body class="install_body">

<div class="wrapper " align="center">

	<div id="install_container" >
 
	<div id="full_bar">
		<div class="box_D_noMargin rounded" style="height: 250px;">
			<div class="appPad">
				 <div id="helpdesk_main">
					 <img src="<?php echo $this->baseUrl();?>/uploads/logo.png" alt="Precurio"/><br/>
					 <span style="font-weight: bold;font-size: 11px;padding: 0px 0px 0px 20px;">
					 ....your complete intranet solution
					 </span>
			         	<div class="contentPad_noLineHeight" >
			         		
			                
			                    <div id="admin_body">
			                        <div class="contentPad_noLineHeight">
										<div  id="tab" class="appTabs">
										<?php
										$root = Zend_Registry::get('root');
										require_once($root.'/application/install/views/scripts/check_settings.phtml')
										?>
											<table width="100%" align="center" cellspacing="10" cellpadding="0">
											   <tr align="center">
											      <td style="width: 25%;">
											          <a href="<?php echo $this->baseUrl();?>/install/upgrade" >
											          	<img src="<?php echo $this->baseUrl();?>/uploads/upgrade.png" />
											         <br/> <?php echo $this->translate("Upgrade Existing Installation");?> </a>   
											      </td>
											      <td style="width: 25%;">
											         <a href="<?php echo $this->baseUrl();?>/install/install/general">
											         <img src="<?php echo $this->baseUrl();?>/uploads/install.png" />
											         <br/>
											         <?php echo $this->translate("New Installtion");?></a>
											      </td>
											    </tr>
											 </table>
									 	</div> 
			                        </div>
			                         
			            </div>
				 </div>
			</div>
		</div>
	</div>
	</div>    
</div>         
</body>
	<?php echo $this->headScript();?>